(set-logic QF_AUFBV )
(declare-fun i1 () (Array (_ BitVec 32) (_ BitVec 8) ) )
(declare-fun i2 () (Array (_ BitVec 32) (_ BitVec 8) ) )
(declare-fun i3 () (Array (_ BitVec 32) (_ BitVec 8) ) )
(declare-fun i4 () (Array (_ BitVec 32) (_ BitVec 8) ) )
(declare-fun i5 () (Array (_ BitVec 32) (_ BitVec 8) ) )
(declare-fun i6 () (Array (_ BitVec 32) (_ BitVec 8) ) )
(declare-fun G1 () (Array (_ BitVec 32) (_ BitVec 8) ) )
(declare-fun G2 () (Array (_ BitVec 32) (_ BitVec 8) ) )
(declare-fun G3 () (Array (_ BitVec 32) (_ BitVec 8) ) )
(declare-fun G4 () (Array (_ BitVec 32) (_ BitVec 8) ) )
(declare-fun GG1 () (Array (_ BitVec 32) (_ BitVec 8) ) )
(declare-fun GG2 () (Array (_ BitVec 32) (_ BitVec 8) ) )
(assert (and  (and  (=  (_ bv0 32) (concat  (select  in5 (_ bv3 32) ) (concat  (select  in5 (_ bv2 32) ) (concat  (select  in5 (_ bv1 32) ) (select  in5 (_ bv0 32) ) ) ) ) ) (=  false (=  (_ bv0 32) (concat  (select  in6 (_ bv3 32) ) (concat  (select  in6 (_ bv2 32) ) (concat  (select  in6 (_ bv1 32) ) (select  in6 (_ bv0 32) ) ) ) ) ) ) ) (=  (_ bv4294967291 32) (concat  (select  in2 (_ bv3 32) ) (concat  (select  in2 (_ bv2 32) ) (concat  (select  in2 (_ bv1 32) ) (select  in2 (_ bv0 32) ) ) ) ) ) ) )
(check-sat)
(exit)
